pipeline {
    agent any
    parameters {
      booleanParam(name: 'REMOTE', defaultValue: false)
        string(name: "IP", defaultValue: "xx.xx.xx.xx", description: "Ip address")
    }
    stages {
        stage('Run Script') {
            steps {
                sh 'echo "Hello script is about run"'
            }
        }
    stage ('Deploy') {
        when {
                expression { return params.REMOTE }
            }
      steps{
          sshagent(credentials : ['test-server']) {
            sh "ssh -o StrictHostKeyChecking=no ubuntu@'${params.IP}' mkdir -p /home/ubuntu/registry/config/schema"
            sh "scp ${WORKSPACE}/registry/docker-compose.yml  ubuntu@'${params.IP}':/home/ubuntu/registry/"
            sh "scp ${WORKSPACE}/registry/testschema.json  ubuntu@'${params.IP}':/home/ubuntu/registry/config/schema/"
            sh "scp ${WORKSPACE}/registry/script.sh  ubuntu@'${params.IP}':/home/ubuntu/registry/"
            sh "ssh -o StrictHostKeyChecking=no ubuntu@'${params.IP}' chmod +x /home/ubuntu/registry/script.sh"
            sh "ssh -o StrictHostKeyChecking=no ubuntu@'${params.IP}' 'cd /home/ubuntu/registry && sh script.sh'"
          }
       }
    }
  }
}
