version: '3.3'

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_PORT: 5432
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: admin
      #KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: https://test-devops.uniteframework.io/auth
    image: dockerhub/sunbird-rc-keycloak:latest  # jboss/keycloak
    volumes:
      - realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
    local-keycloak:
volumes:
  realm-export.json:
