pipeline {
    agent any
    parameters {
      booleanParam(name: 'REMOTE', defaultValue: false)
	string(name: "IP", defaultValue: "xx.xx.xx.xx", description: "Ip address")
    }
    stages {
        stage('Run Script') {
            steps {
                sh 'echo "Hello script is about run"'
            }
        }    
    stage ('Deploy') {
	when {
                expression { return params.REMOTE }
            }
      steps{
          sshagent(credentials : ['test-server']) {
	    sh "ssh -o StrictHostKeyChecking=no ubuntu@'${params.IP}' mkdir -p /home/ubuntu/greylog"
            sh "scp ${WORKSPACE}/greylog/docker-compose.yml  ubuntu@'${params.IP}':/home/ubuntu/greylog/"
            sh "scp ${WORKSPACE}/greylog/script.sh  ubuntu@'${params.IP}':/home/ubuntu/greylog/"
            sh "ssh -o StrictHostKeyChecking=no ubuntu@'${params.IP}' chmod +x /home/ubuntu/greylog/script.sh"
            sh "ssh -o StrictHostKeyChecking=no ubuntu@'${params.IP}' 'cd /home/ubuntu/greylog && sh script.sh'"
          }
       }
    }
  }
}

